version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=wspa_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=wspa_db_2024
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgressql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@wspa.com
      - PGADMIN_DEFAULT_PASSWORD=wspa_2024
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=wspa_db
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=wspa_db_2024
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=wspa_db_2024
      - PMA_HOST=mysql
    ports:
      - 8080:80


